<?php

namespace Database\Seeders;

use App\Models\Department;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $departments = [
            ['id' => '1', 'name' => 'Bogotá', 'country_id' => '4'],
            ['id' => '2', 'name' => 'Amazonas', 'country_id' => '4'],
            ['id' => '3', 'name' => 'Antioquia', 'country_id' => '4'],
            ['id' => '4', 'name' => 'Arauca', 'country_id' => '4'],
            ['id' => '5', 'name' => 'Archipiélago de San Andrés, Providencia y Santa Catalina', 'country_id' => '4'],
            ['id' => '6', 'name' => 'Atlantico', 'country_id' => '4'],
            ['id' => '7', 'name' => 'Bolivar', 'country_id' => '4'],
            ['id' => '8', 'name' => 'Boyaca', 'country_id' => '4'],
            ['id' => '9', 'name' => 'Caldas', 'country_id' => '4'],
            ['id' => '10', 'name' => 'Caqueta', 'country_id' => '4'],
            ['id' => '11', 'name' => 'Casanare', 'country_id' => '4'],
            ['id' => '12', 'name' => 'Cauca', 'country_id' => '4'],
            ['id' => '13', 'name' => 'Cesar', 'country_id' => '4'],
            ['id' => '14', 'name' => 'Choco', 'country_id' => '4'],
            ['id' => '15', 'name' => 'Cordoba', 'country_id' => '4'],
            ['id' => '16', 'name' => 'Cundinamarca', 'country_id' => '4'],
            ['id' => '17', 'name' => 'Guainia', 'country_id' => '4'],
            ['id' => '18', 'name' => 'Guaviare', 'country_id' => '4'],
            ['id' => '19', 'name' => 'Huila', 'country_id' => '4'],
            ['id' => '20', 'name' => 'La Guajira', 'country_id' => '4'],
            ['id' => '21', 'name' => 'Magdalena', 'country_id' => '4'],
            ['id' => '22', 'name' => 'Meta', 'country_id' => '4'],
            ['id' => '23', 'name' => 'Narino', 'country_id' => '4'],
            ['id' => '24', 'name' => 'Norte de Santander', 'country_id' => '4'],
            ['id' => '25', 'name' => 'Putumayo', 'country_id' => '4'],
            ['id' => '26', 'name' => 'Quindio', 'country_id' => '4'],
            ['id' => '27', 'name' => 'Risaralda', 'country_id' => '4'],
            ['id' => '28', 'name' => 'Santander', 'country_id' => '4'],
            ['id' => '29', 'name' => 'Sucre', 'country_id' => '4'],
            ['id' => '30', 'name' => 'Tolima', 'country_id' => '4'],
            ['id' => '31', 'name' => 'Valle del Cauca', 'country_id' => '4'],
            ['id' => '32', 'name' => 'Vaupes', 'country_id' => '4'],
            ['id' => '33', 'name' => 'Vichada', 'country_id' => '4'],
            ['id' => '34', 'name' => 'Extranjero', 'country_id' => '4'],
            ['id' => '35', 'name' => 'Antofagasta', 'country_id' => '3'],
            ['id' => '36', 'name' => 'Arica y Parinacota', 'country_id' => '3'],
            ['id' => '37', 'name' => 'Atacama', 'country_id' => '3'],
            ['id' => '38', 'name' => 'Aysén del General Carlos Ibáñez del Campo', 'country_id' => '3'],
            ['id' => '39', 'name' => 'Biobío', 'country_id' => '3'],
            ['id' => '40', 'name' => 'Coquimbo', 'country_id' => '3'],
            ['id' => '41', 'name' => 'La Araucanía', 'country_id' => '3'],
            ['id' => '42', 'name' => 'Libertador General Bernardo O\'Higgins', 'country_id' => '3'],
            ['id' => '43', 'name' => 'Los Lagos', 'country_id' => '3'],
            ['id' => '44', 'name' => 'Los Ríos', 'country_id' => '3'],
            ['id' => '45', 'name' => 'Magallanes y de la Antártica Chilena', 'country_id' => '3'],
            ['id' => '46', 'name' => 'Maule', 'country_id' => '3'],
            ['id' => '47', 'name' => 'Metropolitana de Santiago', 'country_id' => '3'],
            ['id' => '48', 'name' => 'Ñuble', 'country_id' => '3'],
            ['id' => '49', 'name' => 'Tarapaca', 'country_id' => '3'],
            ['id' => '50', 'name' => 'Valparaiso', 'country_id' => '3'],
            ['id' => '88', 'name' => 'Madrid', 'country_id' => '9'],
            ['id' => '89', 'name' => 'Barcelona', 'country_id' => '9'],
            ['id' => '90', 'name' => 'Valencia', 'country_id' => '9'],
            ['id' => '91', 'name' => 'Sevilla', 'country_id' => '9'],
            ['id' => '92', 'name' => 'Alicante', 'country_id' => '9'],
            ['id' => '93', 'name' => 'Malaga', 'country_id' => '9'],
            ['id' => '94', 'name' => 'Murcia', 'country_id' => '9'],
            ['id' => '95', 'name' => 'Cadiz', 'country_id' => '9'],
            ['id' => '96', 'name' => 'Vizcaya', 'country_id' => '9'],
            ['id' => '97', 'name' => 'Baleares', 'country_id' => '9'],
            ['id' => '98', 'name' => 'A Coruna', 'country_id' => '9'],
            ['id' => '99', 'name' => 'Las Palmas', 'country_id' => '9'],
            ['id' => '100', 'name' => 'Asturias', 'country_id' => '9'],
            ['id' => '101', 'name' => 'Santa Cruz de Tenerife', 'country_id' => '9'],
            ['id' => '102', 'name' => 'Zaragoza', 'country_id' => '9'],
            ['id' => '103', 'name' => 'Pontevedra', 'country_id' => '9'],
            ['id' => '104', 'name' => 'Granada', 'country_id' => '9'],
            ['id' => '105', 'name' => 'Tarragona', 'country_id' => '9'],
            ['id' => '106', 'name' => 'Cordoba', 'country_id' => '9'],
            ['id' => '107', 'name' => 'Girona', 'country_id' => '9'],
            ['id' => '108', 'name' => 'Gipuzkoa', 'country_id' => '9'],
            ['id' => '109', 'name' => 'Almeria', 'country_id' => '9'],
            ['id' => '111', 'name' => 'Badajoz', 'country_id' => '9'],
            ['id' => '112', 'name' => 'Navarra', 'country_id' => '9'],
            ['id' => '113', 'name' => 'Jaen', 'country_id' => '9'],
            ['id' => '114', 'name' => 'Cantabria', 'country_id' => '9'],
            ['id' => '115', 'name' => 'Castellón', 'country_id' => '9'],
            ['id' => '116', 'name' => 'Huelva', 'country_id' => '9'],
            ['id' => '117', 'name' => 'Valladolid', 'country_id' => '9'],
            ['id' => '118', 'name' => 'Ciudad Real', 'country_id' => '9'],
            ['id' => '119', 'name' => 'Leon', 'country_id' => '9'],
            ['id' => '120', 'name' => 'Lleida', 'country_id' => '9'],
            ['id' => '121', 'name' => 'Caceres', 'country_id' => '9'],
            ['id' => '122', 'name' => 'Albacete', 'country_id' => '9'],
            ['id' => '123', 'name' => 'Burgos', 'country_id' => '9'],
            ['id' => '124', 'name' => 'Salamanca', 'country_id' => '9'],
            ['id' => '125', 'name' => 'Lugo', 'country_id' => '9'],
            ['id' => '126', 'name' => 'Alava', 'country_id' => '9'],
            ['id' => '127', 'name' => 'La Rioja', 'country_id' => '1'],
            ['id' => '128', 'name' => 'Ourense', 'country_id' => '9'],
            ['id' => '129', 'name' => 'Guadalajara', 'country_id' => '9'],
            ['id' => '130', 'name' => 'Huesca', 'country_id' => '9'],
            ['id' => '131', 'name' => 'Cuenca', 'country_id' => '9'],
            ['id' => '132', 'name' => 'Zamora', 'country_id' => '9'],
            ['id' => '133', 'name' => 'Palencia', 'country_id' => '9'],
            ['id' => '134', 'name' => 'Avila', 'country_id' => '9'],
            ['id' => '135', 'name' => 'Segovia', 'country_id' => '9'],
            ['id' => '136', 'name' => 'Teruel', 'country_id' => '9'],
            ['id' => '137', 'name' => 'Soria', 'country_id' => '9'],
            ['id' => '138', 'name' => 'Melilla', 'country_id' => '9'],
            ['id' => '139', 'name' => 'Ceuta', 'country_id' => '9'],
            ['id' => '141', 'name' => 'Buenos Aires', 'country_id' => '1'],
            ['id' => '142', 'name' => 'Catamarca', 'country_id' => '1'],
            ['id' => '143', 'name' => 'Chaco', 'country_id' => '1'],
            ['id' => '144', 'name' => 'Chubut', 'country_id' => '1'],
            ['id' => '145', 'name' => 'Cordoba', 'country_id' => '1'],
            ['id' => '146', 'name' => 'Corrientes', 'country_id' => '1'],
            ['id' => '147', 'name' => 'Entre Rios', 'country_id' => '1'],
            ['id' => '148', 'name' => 'Formosa', 'country_id' => '1'],
            ['id' => '149', 'name' => 'Formosa', 'country_id' => '1'],
            ['id' => '150', 'name' => 'Jujuy', 'country_id' => '1'],
            ['id' => '151', 'name' => 'La Pampa', 'country_id' => '1'],
            ['id' => '152', 'name' => 'La Rioja', 'country_id' => '1'],
            ['id' => '153', 'name' => 'Mendoza', 'country_id' => '1'],
            ['id' => '154', 'name' => 'Mendoza', 'country_id' => '1'],
            ['id' => '155', 'name' => 'Misiones', 'country_id' => '1'],
            ['id' => '156', 'name' => 'Neuquen', 'country_id' => '1'],
            ['id' => '157', 'name' => 'Rio Negro', 'country_id' => '1'],
            ['id' => '158', 'name' => 'Salta', 'country_id' => '1'],
            ['id' => '160', 'name' => 'San Luis', 'country_id' => '1'],
            ['id' => '161', 'name' => 'Santa Cruz', 'country_id' => '2'],
            ['id' => '162', 'name' => 'Santa Fe', 'country_id' => '1'],
            ['id' => '163', 'name' => 'Santiago del Estero', 'country_id' => '1'],
            ['id' => '164', 'name' => 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'country_id' => '1'],
            ['id' => '165', 'name' => 'Tucuman', 'country_id' => '1'],
            ['id' => '166', 'name' => 'Beni', 'country_id' => '2'],
            ['id' => '167', 'name' => 'Chuquisaca', 'country_id' => '2'],
            ['id' => '168', 'name' => 'Cochabamba', 'country_id' => '2'],
            ['id' => '169', 'name' => 'La Paz', 'country_id' => '2'],
            ['id' => '170', 'name' => ' Oruro', 'country_id' => '2'],
            ['id' => '171', 'name' => 'Pando', 'country_id' => '2'],
            ['id' => '172', 'name' => 'Potosi', 'country_id' => '2'],
            ['id' => '173', 'name' => ' Santa Cruz', 'country_id' => '2'],
            ['id' => '174', 'name' => ' Tarija', 'country_id' => '2'],
            ['id' => '175', 'name' => ' Tarija', 'country_id' => '2'],
            ['id' => '176', 'name' => ' San José', 'country_id' => '5'],
            ['id' => '177', 'name' => ' Alajuela', 'country_id' => '5'],
            ['id' => '178', 'name' => 'Cartago', 'country_id' => '5'],
            ['id' => '179', 'name' => 'Heredia', 'country_id' => '5'],
            ['id' => '180', 'name' => 'Guanacaste', 'country_id' => '5'],
            ['id' => '181', 'name' => 'Puntarenas', 'country_id' => '5'],
            ['id' => '182', 'name' => ' Limón', 'country_id' => '5'],
            ['id' => '183', 'name' => ' Limón', 'country_id' => '5'],
            ['id' => '184', 'name' => 'Pinar del Rio', 'country_id' => '6'],
            ['id' => '185', 'name' => 'Artemisa', 'country_id' => '6'],
            ['id' => '186', 'name' => 'Mayabeque', 'country_id' => '6'],
            ['id' => '187', 'name' => 'La Habana', 'country_id' => '6'],
            ['id' => '188', 'name' => 'Matanzas', 'country_id' => '6'],
            ['id' => '189', 'name' => 'Cienfuegos', 'country_id' => '6'],
            ['id' => '190', 'name' => 'Villa Clara', 'country_id' => '6'],
            ['id' => '191', 'name' => 'Sancti Spiritus', 'country_id' => '6'],
            ['id' => '192', 'name' => 'Ciego de Avila', 'country_id' => '6'],
            ['id' => '193', 'name' => 'Camaguey', 'country_id' => '6'],
            ['id' => '194', 'name' => 'Las Tunas', 'country_id' => '6'],
            ['id' => '195', 'name' => 'Holguin', 'country_id' => '6'],
            ['id' => '196', 'name' => 'Granma', 'country_id' => '6'],
            ['id' => '197', 'name' => 'Santiago de Cuba', 'country_id' => '6'],
            ['id' => '198', 'name' => 'Guantanamo', 'country_id' => '6'],
            ['id' => '199', 'name' => ' Azuay', 'country_id' => '7'],
            ['id' => '200', 'name' => 'Bolivar', 'country_id' => '7'],
            ['id' => '201', 'name' => 'Canar', 'country_id' => '7'],
            ['id' => '202', 'name' => 'Carchi', 'country_id' => '7'],
            ['id' => '203', 'name' => ' Chimborazo', 'country_id' => '7'],
            ['id' => '204', 'name' => 'Cotopaxi', 'country_id' => '7'],
            ['id' => '205', 'name' => 'Cotopaxi', 'country_id' => '7'],
            ['id' => '206', 'name' => ' El Oro', 'country_id' => '7'],
            ['id' => '207', 'name' => ' Esmeraldas', 'country_id' => '7'],
            ['id' => '208', 'name' => 'Galapagos', 'country_id' => '7'],
            ['id' => '209', 'name' => 'Guayas', 'country_id' => '7'],
            ['id' => '210', 'name' => 'Imbabura', 'country_id' => '7'],
            ['id' => '211', 'name' => 'Loja', 'country_id' => '7'],
            ['id' => '212', 'name' => 'Los Rios', 'country_id' => '7'],
            ['id' => '213', 'name' => 'Manabi', 'country_id' => '7'],
            ['id' => '214', 'name' => 'Morona Santiago', 'country_id' => '7'],
            ['id' => '215', 'name' => 'Napo', 'country_id' => '7'],
            ['id' => '216', 'name' => 'Orellana', 'country_id' => '7'],
            ['id' => '217', 'name' => ' Pastaza', 'country_id' => '7'],
            ['id' => '218', 'name' => 'Pichincha', 'country_id' => '7'],
            ['id' => '219', 'name' => 'Santa Elena', 'country_id' => '7'],
            ['id' => '220', 'name' => 'Santo Domingo de los Tsáchilas ', 'country_id' => '7'],
            ['id' => '221', 'name' => 'Sucumbios', 'country_id' => '7'],
            ['id' => '222', 'name' => 'Sucumbíos ', 'country_id' => '7'],
            ['id' => '223', 'name' => 'Tungurahua', 'country_id' => '7'],
            ['id' => '224', 'name' => 'Zamora Chinchipe', 'country_id' => '7'],
            ['id' => '225', 'name' => 'Ahuachapan', 'country_id' => '8'],
            ['id' => '226', 'name' => 'Cabanas', 'country_id' => '8'],
            ['id' => '227', 'name' => 'Chalatenango	', 'country_id' => '8'],
            ['id' => '228', 'name' => 'Cuscatlan', 'country_id' => '8'],
            ['id' => '229', 'name' => 'La Libertad', 'country_id' => '8'],
            ['id' => '230', 'name' => 'La Paz', 'country_id' => '8'],
            ['id' => '231', 'name' => 'La Union', 'country_id' => '8'],
            ['id' => '232', 'name' => 'Morazan', 'country_id' => '8'],
            ['id' => '233', 'name' => 'San Miguel', 'country_id' => '8'],
            ['id' => '234', 'name' => 'San Salvador', 'country_id' => '8'],
            ['id' => '235', 'name' => 'San Vicente', 'country_id' => '8'],
            ['id' => '236', 'name' => 'Santa Ana', 'country_id' => '8'],
            ['id' => '237', 'name' => 'Sonsonate', 'country_id' => '8'],
            ['id' => '238', 'name' => 'Usulutan', 'country_id' => '8'],


        ];

        foreach ($departments as $key => $value) {
            $department = new Department();
            $department->id = $value['id'];
            $department->country_id = $value['country_id'];
            $department->name = $value['name'];
            $department->save();
        }
    }
}
